config/routes.rb
Rails.application.routes.draw do
  resources :companies
end

app/models/company.rb
class Company < ActiveRecord::Base
	validates :name, :ceo, :address, :state, :zip, presence: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def new
  	@company = Company.new
  end

  def create
  	@company = Company.new(company_params)
  	if @company.save
  		redirect_to companies_path
  	else 
  		render :new
  	end   
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update

    @company = Company.find(params[:id])
    if @company.update(company_params)
      redirect_to companies_path
    else
      render :edit
    end

    
  end
private
  def company_params
    company_params = params.require(:company).
      permit(:name, :ceo, :address, :state, :zip)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

    <ul>
    <% @company.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :ceo %><br />
    <%= f.text_field :ceo %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= link_to "Cancel", companies_path %>

app/views/companies/edit.html.erb
<h1>Update Company</h1>
<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Companies</h1>
<%= link_to "Add New Company", new_company_path %>
<% @companies.each do |company| %>

<p>
    <arcticle>
        <header>
            <%= "Name: " + company.name  %>
            <br>
            <%= "CEO: " + company.ceo  %>
            <br>
            <%= "Address: " + company.address %>
            <br>
            <%= "State: " + company.state  %>
            <br>
            <%= "Zip: " + company.zip  %> <br />

            
            <%= link_to "Edit", edit_company_path(company)%>
            
        </header>
    </arcticle>
    
</p>
<% end %>

app/views/companies/new.html.erb
<h1>New Company</h1>
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>